### PR TITLE
Adding compatability with authoring tool

### PR DESCRIPTION
**Pull request by davetaz**

### CODE REVIEW

**Comment by jpablo128** [comment]
@davetaz  thanks. I'm sorry I haven't been able to get to this earlier, I'm reviewing it now and trying to figure out some stuff.

**Comment by davetaz** [comment]
No worries. I think i've strayed too far from your initial approach now so you might want to reject this. I didn't realise the PR was still open.

**Comment by davetaz** [comment]
Happy to chat further on what i've been doing with this as the tracking hub is fantastic.

**Comment by jpablo128** [comment]
hi @davetaz, yes, it would be great to chat further and see how you're using this... and if you're still using it.

I've reviewed your PR commit by commit, to get an idea of what you implemented.

It's great to see how somebody else  took it and adapted it to his own needs/use case, as it helps me to see some of the shortcomings of trackingHub. Part of your code definitely belongs in the core trackingHub extension, and some of it -I think- should remain separate, in its own extensions (since trackingHub is designed to be 'extended' externally), but I still need to get into it in more detail to see... it's a blurry line. Concretely, I think that probably most of the code you've added to trackingHub.js regarding the updateState method should be in your own ODILRSStorage-transportHandler... but I have to think how exactly that can be achieved. I probably have to introduce some conceptual enhancements to trackingHub to accommodate things like this. I wouldn't say you've 'strayed', since I provided no information whatsoever about what should be a fix/improvement to the core, and what should be implemented as external extensions...

So, I definitely think trackingHub can be improved based on your contribution, so I'm not going to 'reject' the PR... I'm not sure how to manage these things on github, so here's what I think I'm going to do, let me know what you think:

Locally, I'm going to take your whole PR (your commits reflect the evolution of your development, as you've applied changes/fixes to your own code, so the safest thing -I think- is to get everything, instead of trying to pick isolated things from different commits). THEN, I can begin to separate what will remain in the trackingHub extension from what will be 'migrated' to an external extension/piece of code... I'll have to test and modify trackingHub as I go along.  In 'theory' I should end up with a new version of trackingHub + a new version of YOUR extensions (ODILRSStorage-transport handler... learnify-messageComposer etc...) that would be functionally equivalent to what you have now... that's the theory, maybe there are some things that I can't test (e.g. interaction with ODIS LRS... which I assume is a custom LRS you've built)... so, we'll see. But obviously I want to end up with something that you can use...
    I'll try to add useful commit messages as I work back from 'your version' ... I'm going to try and put all this in a separate branch... at the end, if things work as expected, will merge into master.

I intended to review your PR and give a pretty big overhaul to trackingHub, -including better documentation for users and for developers- and finally I have been able to fit it into my schedule... so, let's see...

This is probably going to take me a few days... I'll keep you posted

Regards

**Comment by davetaz** [comment]
Hi @jpablo128 

Thanks for the reply. Just first to say thanks for your reply, the trackingHub has been a key part of our eLearning deployment in adapt 2. As you can see i've been continually learning how to use the structure of Adapt 2 and I think I'm getting there but it's been time vs my knowledge. 

In order to help I've just added an example data structure that gets sent to our LRS to show you what it looks like. Also I've added a readme alongside it. 

As you say our LRS is custom and focuses on the key statistics while scaling to accommodate the situation where one article/page can exist in many courses for many clients. Clients are separated by theme. 

I don't have much time remaining this year to improve this as I have more pressing needs at work, however my intention was to pick up the trackingHub again in the new year alongside our LRS and see if I could open up a community version for anyone to use. We are the Open Data Institute after all. 

Any help you can give to tidy up my appalling code while keeping the functionality would be most appreciated!

**Comment by jpablo128** [comment]
Thanks @davetaz , this info you've provided is **very** useful. I'm getting deep into this, and I see that I need to make significant changes/improvements to trackingHub  , so it can accommodate external code more cleanly and clearly... which was its main purpose in the first place... it was due for an update, and ... well,  it's a challenge :)  ... I'll keep you posted.

**Comment by jpablo128** [comment]
Dave, I'm closing this PR, but as you know (I emailed you) I merged it locally and then modified everything quite a bit... the new version has changed quite a bit.

**Pull request closed without merging**
